{
  "openapi": "3.1.0",
  "info": {
    "title": "carrier-api",
    "version": "api-1.0",
    "description": "API Портала Перевозчика",
    "contact": {
      "name": "Ivan Donchenko",
      "email": "idonchenko@solvo.ru",
      "url": "solvo.ru"
    },
    "license": {
      "name": "Commercial",
      "url": "https://solvo.ru/license"
    }
  },
  "servers": [
    {
      "url": "https://stoplight.io/mocks/thehunt/yard-apidoc/132102081",
      "description": "Stoplight mocker"
    },
    {
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/oauth/token": {
      "post": {
        "summary": "OAuth token request",
        "description": "Получение OAuth токена для аутентификации в системе",
        "requestBody": {
          "description": "OAuth token request",
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "grant_type": {
                    "enum": [
                      "authorization_code",
                      "refresh_token"
                    ]
                  },
                  "code": {
                    "type": "string",
                    "description": "Authorization code"
                  },
                  "redirect_uri": {
                    "type": "string",
                    "description": "Redirect URI"
                  },
                  "client_id": {
                    "type": "string",
                    "description": "Client ID"
                  },
                  "client_secret": {
                    "type": "string",
                    "description": "Client secret"
                  }
                },
                "required": [
                  "grant_type",
                  "client_id",
                  "client_secret"
                ]
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "grant_type": "authorization_code",
                    "code": "4/P7q7W91a-oMsCeLvIaQm6bTrgtp7",
                    "redirect_uri": "https://example.com/oauth2callback",
                    "client_id": "ваш-client-id",
                    "client_secret": "ваш-client-secret"
                  }
                },
                "Example 2": {
                  "value": {
                    "grant_type": "refresh_token",
                    "refresh_token": "1//0eXABCDEF-ghijklmnopqrstuvwxyzABCDEF",
                    "client_id": "ваш-client-id",
                    "client_secret": "ваш-client-secret"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OAuth token response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "access_token": {
                      "type": "string",
                      "description": "Access token"
                    },
                    "token_type": {
                      "type": "string",
                      "description": "Token type"
                    },
                    "expires_in": {
                      "type": "integer",
                      "description": "Token expiration time"
                    },
                    "refresh_token": {
                      "type": "string",
                      "description": "Refresh token"
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "access_token": "ya29.a0AfH6SMBx-0kzHx8YT1nKhBjLxGJHtLOSO_7VTX8eK0HN_Ew",
                      "token_type": "Bearer",
                      "expires_in": 3600,
                      "refresh_token": "1//0eXABCDEF-ghijklmnopqrstuvwxyzABCDEF"
                    }
                  },
                  "Example 2": {
                    "value": {
                      "access_token": "ya29.b0AfH6SMCx-1lzIy9YU2mLhCkMHtMPTP_8WUY9fL1eL1IN_Fx",
                      "token_type": "Bearer",
                      "expires_in": 3600
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "getOAuthToken",
        "tags": [
          "Аутентификация"
        ]
      }
    },
    "/oauth/revoke": {
      "post": {
        "summary": "OAuth token revocation",
        "description": "Отзыв OAuth токена",
        "requestBody": {
          "description": "OAuth token revocation request",
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string",
                    "description": "Token to revoke"
                  }
                },
                "required": [
                  "token"
                ]
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "token": "ya29.a0AfH6SMBx-0kzHx8YT1nKhBjLxGJHtLOSO_7VTX8eK0HN_Ew"
                  }
                },
                "Example 2": {
                  "value": {
                    "token": "1//0eXABCDEF-ghijklmnopqrstuvwxyzABCDEF"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Token revoked"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "revokeOAuthToken",
        "tags": [
          "Аутентификация"
        ]
      }
    },
    "/oauth/userinfo": {
      "get": {
        "summary": "OAuth userinfo",
        "description": "Получение информации о текущем пользователе",
        "security": [
          {
            "oauth2": []
          }
        ],
        "responses": {
          "200": {
            "description": "Userinfo response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "sub": {
                      "type": "string",
                      "description": "User ID"
                    },
                    "name": {
                      "type": "string",
                      "description": "User name"
                    },
                    "email": {
                      "type": "string",
                      "description": "User email"
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "sub": "123456789",
                      "name": "Иван Иванов",
                      "email": "ivan.ivanov@example.com"
                    }
                  },
                  "Example 2": {
                    "value": {
                      "sub": "987654321",
                      "name": "Анна Петрова",
                      "email": "anna.petrova@example.com"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "getUserInfo",
        "tags": [
          "Аутентификация"
        ]
      }
    },
    "/shipment-rfp": {
      "get": {
        "summary": "Получить список заявок на перевозку",
        "responses": {
          "200": {
            "$ref": "#/components/responses/shipment-rfp-list"
          }
        },
        "description": "Получение списка заявок на перевозку",
        "operationId": "getShipmentRfpList",
        "tags": [
          "Заявки на перевозку"
        ]
      },
      "put": {
        "summary": "Создать новую заявку на перевозку",
        "responses": {
          "201": {
            "$ref": "#/components/responses/shipment-rfp-item"
          }
        },
        "requestBody": {
          "$ref": "#/components/requestBodies/shipment-rfp-data"
        },
        "description": "Создание новой заявки на перевозку",
        "operationId": "createShipmentRfp",
        "tags": [
          "Заявки на перевозку"
        ]
      },
      "parameters": []
    },
    "/shipment-rfp/{id}": {
      "get": {
        "summary": "Получить детали заявки на перевозку",
        "responses": {
          "200": {
            "$ref": "#/components/responses/shipment-rfp-item"
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID заявки на перевозку",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "description": "Получение детальной информации о заявке на перевозку",
        "operationId": "getShipmentRfpDetails",
        "tags": [
          "Заявки на перевозку"
        ]
      },
      "post": {
        "summary": "Обновить заявку на перевозку",
        "responses": {
          "200": {
            "$ref": "#/components/responses/shipment-rfp-item"
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID заявки на перевозку",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/shipment-rfp-item"
        },
        "description": "Обновление информации о заявке на перевозку",
        "operationId": "updateShipmentRfp",
        "tags": [
          "Заявки на перевозку"
        ]
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/id"
        }
      ]
    },
    "/offers": {
      "get": {
        "summary": "Получить список предложений",
        "responses": {
          "200": {
            "$ref": "#/components/responses/offer-list"
          }
        },
        "description": "Получение списка предложений от перевозчиков",
        "operationId": "getOfferList",
        "tags": [
          "Предложения"
        ]
      },
      "put": {
        "summary": "Создать новое предложение",
        "responses": {
          "201": {
            "$ref": "#/components/responses/offer-item-response"
          }
        },
        "requestBody": {
          "$ref": "#/components/requestBodies/offer-data"
        },
        "description": "Создание нового предложения от перевозчика",
        "operationId": "createOffer",
        "tags": [
          "Предложения"
        ]
      },
      "parameters": []
    },
    "/offers/{id}": {
      "get": {
        "summary": "Получить детали предложения",
        "responses": {
          "200": {
            "$ref": "#/components/responses/offer-item-response"
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID предложения",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "description": "Получение детальной информации о предложении",
        "operationId": "getOfferDetails",
        "tags": [
          "Предложения"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/offer-item-request"
        }
      },
      "post": {
        "summary": "Обновить предложение",
        "responses": {
          "200": {
            "description": "Предложение обновлено",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./models/schemas/offer-item.json"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID предложения",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "./models/schemas/offer-item.json"
              }
            }
          }
        },
        "description": "Обновление информации о предложении",
        "operationId": "updateOffer",
        "tags": [
          "Предложения"
        ]
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/id"
        }
      ]
    },
    "/catalogs": {
      "get": {
        "summary": "Получить перечень справочников системы",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/catalog-list"
          }
        },
        "operationId": "getCatalogList",
        "description": "Получение списка справочников системы"
      },
      "put": {
        "summary": "Создать новый справочник",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "201": {
            "$ref": "#/components/responses/catalog-metaitem"
          }
        },
        "operationId": "createCatalog",
        "requestBody": {
          "$ref": "#/components/requestBodies/catalog-metaitem"
        },
        "description": "Создание нового справочника"
      },
      "post": {
        "summary": "Изменить описание справочника",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "202": {
            "$ref": "#/components/responses/catalog-metaitem"
          }
        },
        "operationId": "updateCatalog",
        "requestBody": {
          "$ref": "#/components/requestBodies/catalog-metaitem"
        },
        "description": "Обновление информации о справочнике"
      }
    },
    "/catalogs/{key}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/key"
        }
      ],
      "get": {
        "summary": "Получить описание справочника",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/catalog-metaitem"
          }
        },
        "operationId": "getCatalogByKey",
        "description": "Получение информации о конкретном справочнике"
      },
      "post": {
        "summary": "Изменить запись справочника",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "202": {
            "$ref": "#/components/responses/catalog-item"
          }
        },
        "operationId": "updateCatalogByKey",
        "requestBody": {
          "$ref": "#/components/requestBodies/catalog-item"
        },
        "description": "Обновление информации о конкретном справочнике"
      },
      "put": {
        "summary": "Создать запись справочника",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/catalog-item"
          }
        },
        "operationId": "createCatalogItemByKey",
        "requestBody": {
          "$ref": "#/components/requestBodies/catalog-item"
        },
        "description": "Создание нового элемента в конкретном справочнике"
      }
    },
    "/catalogs/{key}/items/{id}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/key"
        },
        {
          "$ref": "#/components/parameters/id"
        }
      ],
      "get": {
        "summary": "Получить запись справочника",
        "tags": [
          "Справочники"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/catalog-item"
          }
        },
        "operationId": "getCatalogItemById",
        "description": "Получение информации о конкретном элементе справочника"
      }
    },
    "/lists": {
      "get": {
        "summary": "Получить перечень списков",
        "tags": [
          "Списки"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./models/abstract/simple-list.json"
                  }
                }
              }
            }
          }
        },
        "operationId": "getAllLists",
        "description": "Получение списка всех списков"
      }
    },
    "/lists/{key}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/key"
        }
      ],
      "get": {
        "summary": "Получить информацию о списке",
        "tags": [
          "Списки"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./models/abstract/simple-list.json"
                }
              }
            }
          }
        },
        "operationId": "getListByKey",
        "description": "Получение информации о конкретном списке"
      }
    },
    "/lists/{key}/items": {
      "parameters": [
        {
          "$ref": "#/components/parameters/key"
        }
      ],
      "get": {
        "summary": "Получить элементы списка",
        "tags": [
          "Списки"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "type": "array",
                      "items": {
                        "$ref": "./models/abstract/simple-list-item.json"
                      }
                    },
                    {
                      "$ref": "./models/abstract/simple-list.json"
                    }
                  ]
                }
              }
            }
          }
        },
        "operationId": "getListItemsByKey",
        "description": "Получение элементов конкретного списка"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://example.com/auth/realms/master/protocol/openid-connect/auth",
            "tokenUrl": "https://example.com/auth/realms/master/protocol/openid-connect/token",
            "refreshUrl": "",
            "scopes": {
              "userinfo": "userinfo"
            }
          }
        }
      }
    },
    "responses": {
      "shipment-rfp-list": {
        "description": "Список заявок на перевозку",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "items": {
                  "type": "array",
                  "items": {
                    "$ref": "./models/schemas/shipment-rfp-item.json"
                  }
                },
                "page-info": {
                  "$ref": "./models/schemas/pagination.json"
                },
                "meta": {
                  "$ref": "./models/abstract/domain-meta.json"
                }
              }
            }
          }
        }
      },
      "offer-list": {
        "description": "Список предложений к заявке на перевозку",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "meta",
                "items"
              ],
              "properties": {
                "meta": {
                  "$ref": "./models/abstract/domain-meta.json"
                },
                "items": {
                  "type": "array",
                  "items": {
                    "$ref": "./models/schemas/offer-item.json"
                  }
                },
                "page-info": {
                  "$ref": "./models/schemas/pagination.json"
                }
              }
            }
          }
        }
      },
      "shipment-rfp-item": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/shipment-rfp-item.json"
            }
          }
        }
      },
      "offer-item-response": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/offer-item.json"
            }
          }
        }
      },
      "catalog-metaitem": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/catalog-metaitem.json"
            }
          }
        },
        "description": "Объект Справочник"
      },
      "catalog-item": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/catalog-item.json"
            }
          }
        },
        "description": "Запись элемента справочника"
      },
      "catalog-list": {
        "description": "Список справочников",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "page-info": {
                  "$ref": "./models/schemas/pagination.json"
                },
                "catalogs": {
                  "type": "array",
                  "items": {
                    "$ref": "./models/abstract/rich-list.json"
                  }
                }
              }
            }
          }
        }
      },
      "catalog-item-list": {
        "description": "Справочник целиком",
        "content": {
          "application/json": {
            "schema": {
              "required": [
                "items"
              ],
              "properties": {
                "items": {
                  "type": "array",
                  "items": {
                    "$ref": "./models/schemas/catalog-item.json"
                  }
                },
                "meta": {
                  "$ref": "./models/schemas/catalog-metaitem.json"
                },
                "page-info": {
                  "$ref": "./models/schemas/pagination.json"
                }
              },
              "type": "object"
            }
          }
        }
      }
    },
    "requestBodies": {
      "shipment-rfp-item": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/shipment-rfp-item.json"
            }
          }
        }
      },
      "offer-item-request": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/offer-item.json"
            }
          }
        }
      },
      "catalog-metaitem": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/catalog-metaitem.json"
            }
          }
        },
        "description": "Атрибуты редактируемого справочника"
      },
      "catalog-item": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/catalog-item.json"
            }
          }
        },
        "description": "Объект Запись Справочника"
      },
      "shipment-rfp-data": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/shipment-rfp-data.json"
            }
          }
        }
      },
      "offer-data": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "./models/schemas/offer-data.json"
            }
          }
        }
      }
    },
    "parameters": {
      "id": {
        "name": "id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "format": "uuid"
        },
        "description": "Идентификатор записи"
      },
      "key": {
        "name": "key",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "format": "hostname"
        },
        "description": "Ключ/код коллекции",
        "style": "label"
      }
    }
  },
  "tags": [
    {
      "name": "Аутентификация",
      "description": "Операции, связанные с аутентификацией"
    },
    {
      "name": "Заявки на перевозку",
      "description": "Операции с заявками на перевозку"
    },
    {
      "name": "Предложения",
      "description": "Операции с предложениями перевозчиков"
    },
    {
      "name": "Справочники",
      "description": "Операции со справочниками системы"
    },
    {
      "name": "Списки",
      "description": "Операции со списками"
    }
  ]
}